// Bundles CodeMirror 6 into www/jvscrpt_and_css_extra/codemirror-bundle.js
// as an IIFE exposing the global `CM`.
//
//   node build_tools/build_cm.js [--watch]
//
// Writes straight into www/ rather than emitting beside this script and asking
// for a manual copy, which is a documented footgun in the Revery Notebook
// version ("Then copy codemirror-bundle.js to your jvscrpt_and_css_extra/").
//
// The output is generated and committed. Do not edit it; edit cm_entry_tex.js
// and rebuild.

const esbuild = require('esbuild');
const path = require('path');
const fs = require('fs');

const ROOT = path.resolve(__dirname, '..');
const OUT = path.join(ROOT, 'www/jvscrpt_and_css_extra/codemirror-bundle.js');
const WATCH = process.argv.includes('--watch');

const options = {
  entryPoints: [path.join(__dirname, 'cm_entry_tex.js')],
  bundle: true,
  format: 'iife',
  globalName: 'CM',
  outfile: OUT,
  minify: true,
  platform: 'browser',
  target: ['es2020'],
  banner: { js: '/* Generated by build_tools/build_cm.js - do not edit. Edit cm_entry_tex.js. */' },
  logLevel: 'info'
};

(async () => {
  if (WATCH) {
    const ctx = await esbuild.context(options);
    await ctx.watch();
    console.log('watching cm_entry_tex.js ...');
    return;
  }
  await esbuild.build(options);
  const kb = (fs.statSync(OUT).size / 1024).toFixed(0);
  console.log(`\n[ok] ${path.relative(ROOT, OUT)}  ${kb} KB`);
})().catch(err => { console.error('Build failed:', err); process.exit(1); });
